# Generated by Django 2.1.3 on 2019-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantillas_presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=1024)),
                ('archivo', models.FileField(upload_to='plantillas/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
